### ISSUE TITLE
Remove main.py?

### ISSUE THREAD

**Issue by firefly-cpp** [alenrajsp/tcxreader#11]
@alenrajsp, one similar example is already in the examples folder.

**Comment by alenrajsp** [comment]
Removed main.py in the [commit](https://github.com/alenrajsp/tcxreader/commit/67ae2f088c36989a7f8ba876db8d3c5e3be112ca). The newly built project is also available on the [pypi](https://pypi.org/manage/project/tcxreader/release/0.3.14/).
