### ISSUE TITLE
Add support for  SUP activities

### ISSUE THREAD

**Issue by firefly-cpp** [alenrajsp/tcxreader#14]
Test file: https://github.com/firefly-cpp/tcx-test-files

**Comment by alenrajsp** [comment]
Added support for sup files. Relevant commits in 5767f7bd9d30665e1f1372a6a59a4d3d7345ddd9 and acef31f5c443af2cbdf5b71da5b370f547b58294 .
The new version is passing the tests and is also updated on the pypi.
