### ISSUE TITLE
Value conversions

### ISSUE THREAD

**Issue by rpstar** [alenrajsp/tcxreader#19]
FYI, in trying to read some tcx files from Google fit I had to change several locations where it tried to cast to int to:

int(float(textalue))

because the file had things like HeartRate as 86.0.   Without that you get this error:

https://stackoverflow.com/questions/1841565/valueerror-invalid-literal-for-int-with-base-10

Ex: line 130 of tcxreader:
tcx_point.hr_value = int(float(heart_rate.text))

**Comment by alenrajsp** [comment]
@rpstar thank you! I have [updated](https://github.com/alenrajsp/tcxreader/commit/ddcd8253a13e99067ab3d77ae1b1f1614611d5bf)the project.
