### ISSUE TITLE
Current TCXReader does not appear to support daylight savings formats

### ISSUE THREAD

**Issue by amandamch** [alenrajsp/tcxreader#22]
Using a file that was recorded during UK daylight savings time, the datetime for the trackpoints includes `+01:00`, and trying to use such a file in the TCXReader produces the following ValueError:

`ValueError: time data '2022-10-25T19:33:35.000+01:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`

This does not appear fixable on my end just by removing characters from each datetime in Python, as the error is related to the `tcxReader.read()` function

**Comment by alenrajsp** [comment]
Thank you for the raised issue. The new release should be available today!

**Comment by alenrajsp** [comment]
I have checked the issued fix from #21 from @jlrobins . I have added **another string format** against which the trackpoint date should be checked and then tried it with your value. 
The new string format `"%Y-%m-%dT%H:%M:%S%z"` should work for your case. I am preparing a release right now.

**Comment by alenrajsp** [comment]
@amandamch please check out the new release. The issue should be fixed.
