### ISSUE TITLE
No trackpoints read out when position data is missing

### ISSUE THREAD

**Issue by pepeheeren** [alenrajsp/tcxreader#42]
Hi,
I'm using the tcxreader in a personal project, and it works nicely with most of my tcx-files exported from Garmin. However for this one file where positional data of the trackpoints is missing (but timestamps, heartrate data etc. still available) it only reads out very little general information (author, activity_type), but tcx.trackpoints is a completely empty list. I am assuming there's an exception built in during the parsing of the file if no positional data is available? Would it be feasible/desirable to change that, so that all available data is read in and stored, even if some parameters are missing?
I have attached the relevant tcx-file for reference:
[activity_12702654569.tcx.txt](https://github.com/alenrajsp/tcxreader/files/13463427/activity_12702654569.tcx.txt)

Cheers, Paul

**Comment by pepeheeren** [comment]
Ok, sometimes digging into the code before raising an issue helps - I found the option of setting "only_gps" to false in the read-method. This resolves it :)

**Comment by alenrajsp** [comment]
Thank you for raising this issue and using this library. Maybe I can update the readme so that it is pointed out more clearly.

**Comment by pnposch** [comment]
Hi @alenrajsp , thanks for your great project, much appreciated. I ran into the same problem as @pepeheeren also with a similar project and second your idea of pointing this out more prominently in the docu. Thanks

**Comment by alenrajsp** [comment]
I've addressed the suggestion in the latest readme.
