### ISSUE TITLE
Value Conversion Error - Cadence

### ISSUE THREAD

**Issue by rwinklerwilkes** [alenrajsp/tcxreader#46]
Similar issue to #19 - if the TCX file contains Cadence as a float value, e.g. '86.0' it will cause "ValueError: invalid literal for int() with base 10: '0.0'". If helpful, I've attached a truncated TCX file exported from a Peloton bike which has the issue, saved as .txt to allow Github import.

[Example_Issue.txt](https://github.com/alenrajsp/tcxreader/files/14002735/Example_Issue.txt)

Code on line https://github.com/alenrajsp/tcxreader/blob/9d0f07e4cfcd5e8d4eafb9f5c2ce6eaec91d5693/tcxreader/tcxreader.py#L146 appears to cause the issue. You previously fixed a similar problem for heart rate on https://github.com/alenrajsp/tcxreader/commit/ddcd8253a13e99067ab3d77ae1b1f1614611d5bf.

**Comment by alenrajsp** [comment]
Thanks for the raised issue I will change it to float.

**Comment by alenrajsp** [comment]
@all-contributors
please add @rwinklerwilkes for bug reports.

**Comment by alenrajsp** [comment]
@rwinklerwilkes 
I have fixed the raised issue in new release 0.4.9. Cadence is now parsed like.
`                try:
                    tcx_point.cadence = int(float(trackpoint_data.text))
`

I am closing the issue for now.
