### ISSUE TITLE
Read error with missing HR data values

### ISSUE THREAD

**Issue by simonpickering** [alenrajsp/tcxreader#47]
If there is missing HR data in a TCX file, the read code is crashing for me with the following error:

...\lib\site-packages\tcxreader\tcxreader.py", line 144, in trackpoint_parser
    tcx_point.hr_value = int(float(heart_rate.text))
TypeError: float() argument must be a string or a number, not 'NoneType'

Looking inside the TCX there are some missing values:
...
```
<HeartRateBpm>
  <Value></Value>
</HeartRateBpm>
```
...

I guess this may also apply to other datafields too if the sensor falls out during a ride.

I'm using Python 3.9 (I know, a bit behind the times, but embedded platform) and tcxreader-0.4.6 via pip3.

**Comment by alenrajsp** [comment]
I am solving the issue and will provide an update soon. This will be today/tommorow in the new version.

**Comment by alenrajsp** [comment]
@simonpickering can you please provide also example TCX file so I can test it before new version release.

**Comment by simonpickering** [comment]
I don't have anything particularly small/anonymised to hand I'm afraid. I'm happy to test for you though, or I expect you can generate the same behaviour by editing a working TCX to create an empty HeartRateBpm value.

Let me know if I can help, thanks for looking at it so swiftly.

**Comment by alenrajsp** [comment]
@all-contributors
please add @simonpickering for bug reports.

**Comment by alenrajsp** [comment]
@simonpickering please check the new release 0.4.9 which should solve all your issues. Also please check the updated readme section [regarding missing data handling](https://github.com/alenrajsp/tcxreader?tab=readme-ov-file#missing-data-handling). Closing for now.
