### ISSUE TITLE
AssertionErrors

### ISSUE THREAD

**Issue by firefly-cpp** [alenrajsp/tcxreader#6]
@alenrajsp, pytest is failing due to the assertion errors. Please check it out!

def test_hr_max(self):
self.assertEqual(self.tcx.hr_max, None)     ->  **it should be 200**   

There is another **None:**

    def altitude_avg(self):
        self.assertEqual(self.tcx.altitude_avg, None)

**Comment by alenrajsp** [comment]
Thank you.
I have fixed the issue in the latest update (0.3.9). It was related to assigning the value to hr_max (the variable was mispronounced in the tcx generating class).
The new version is available on [pypi](https://pypi.org/project/tcxreader/), *0.3.9*.
