### ISSUE TITLE
Fix linter issues

### ISSUE THREAD

**Issue by firefly-cpp** [alenrajsp/tcxreader#8]
./tests/test_tcxreader.py:4:1: W391 blank line at end of file
./examples/reader_demo.py:4:1: F401 'tcxreader.tcxreader.TCXTrackPoint' imported but unused
./examples/reader_demo.py:18:1: W191 indentation contains tabs
./examples/reader_demo.py:18:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:19:1: W191 indentation contains tabs
./examples/reader_demo.py:19:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:20:1: W191 indentation contains tabs
./examples/reader_demo.py:20:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:21:1: W191 indentation contains tabs
./examples/reader_demo.py:21:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:22:1: W191 indentation contains tabs
./examples/reader_demo.py:22:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:23:1: W191 indentation contains tabs
./examples/reader_demo.py:23:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:24:1: W191 indentation contains tabs
./examples/reader_demo.py:24:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:25:1: W191 indentation contains tabs
./examples/reader_demo.py:25:2: E101 indentation contains mixed spaces and tabs
./examples/reader_demo.py:26:1: W191 indentation contains tabs
./examples/reader_demo.py:26:2: E101 indentation contains mixed spaces and tabs
./tcxreader/tcxreader.py:1:1: F401 'os' imported but unused
./tcxreader/tcxreader.py:6:1: F401 'pathlib.Path' imported but unused
./tcxreader/tcxreader.py:16:5: C901 'TCXReader.read' is too complex (34)
./tcxreader/tcxreader.py:73:21: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./tcxreader/tcxreader.py:87:5: C901 'TCXReader.__find_hi_lo_avg' is too complex (14)
./tcxreader/tcxreader.py:93:36: E711 comparison to None should be 'if cond is not None:'
./tcxreader/tcxreader.py:95:37: E711 comparison to None should be 'if cond is not None:'
./tcxreader/tcxreader.py:97:35: E711 comparison to None should be 'if cond is not None:'
./tcxreader/tests/test_reader.py:3:1: F401 'tcxreader.tcxreader.TCXTrackPoint' imported but unused
./tcxreader/tests/test_reader.py:3:1: F401 'tcxreader.tcxreader.TCXExercise' imported but unused
./tcxreader/tests/conftest.py:3:1: E302 expected 2 blank lines, found 1
2     C901 'TCXReader.read' is too complex (34)
9     E101 indentation contains mixed spaces and tabs
1     E302 expected 2 blank lines, found 1
3     E711 comparison to None should be 'if cond is not None:'
1     E712 comparison to True should be 'if cond is True:' or 'if cond:'
5     F401 'tcxreader.tcxreader.TCXTrackPoint' imported but unused
9     W191 indentation contains tabs
1     W391 blank line at end of file

**Comment by alenrajsp** [comment]
Fixed where possible. Thank you @firefly-cpp
